import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Project from '@/components/Project'
import Portrait from '@/components/Portrait'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="w-full h-full bg-zinc-100 p-8">
        <main className="w-full md:w-[calc(100%-2rem)] mx-auto bg-zinc-50 p-4 rounded border shadow-md">
          <div className={styles.description}>
            Hi
          </div>
        </main>
      </div> */}
      <div className="w-full h-full bg-white">
        <div className="flex flex-col">
          <div className="flex h-[5rem] border-b">
            <div className="w-screen-layout-offset border-r"></div>
            <div className="flex-grow"></div>
            <div className="w-screen-layout-offset border-l"></div>
          </div>
          <div className="flex flex-grow">
            <div className="w-screen-layout-offset border-r"></div>
            <main className={`${styles.Main} flex-grow`}>
              <header className="flex justify-between">
                <div className="flex flex-col p-4">
                  <h1 className={`${styles.Nameplate} tracking-tight`}>Julian Atkin</h1>
                  <h2 className="mb-4">Full Stack Engineer</h2>
                  <section className="mb-16">
                    Hi, I'm Julian! My mission is to build accessible and usable web technologies that make the world a better place.
                  </section>
                </div>
                <div className="relative object-cover min-w-[12rem] border-l">
                  <Portrait></Portrait>
                </div>
              </header>
              <section className="border-t">
                <h3 className="p-4 border-b ">Projects</h3>
                <div className="w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 [&>*]:p-4 [&>*]:bg-white gap-px bg-zinc-200">
                  <Project title="Grid Chat">

                  </Project>
                  <Project title="Croppy">

                  </Project>
                  <Project title="League of Legends Ability Quiz">

                  </Project>
                  <Project title="Fake Instagram Post Generator">

                  </Project>

                </div>
              </section>
            </main>
            <div className="w-screen-layout-offset border-l"></div>
          </div>
          <div className="flex h-[4rem] border-t">
            <div className="w-screen-layout-offset border-r"></div>
            <div className="flex-grow"></div>
            <div className="w-screen-layout-offset border-l"></div>
          </div>
        </div>
      </div>
    </>
  )
}
